# Generated by Django 4.2.7 on 2023-12-15 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('name', models.TextField()),
                ('vendor_code', models.BigIntegerField()),
                ('price', models.IntegerField()),
                ('count', models.IntegerField()),
                ('sizes', models.ManyToManyField(to='store.size')),
                ('type_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.type')),
            ],
        ),
    ]
