# Generated by Django 4.2.7 on 2023-11-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trousers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('vendore_code', models.BigIntegerField()),
                ('price', models.IntegerField()),
                ('count', models.IntegerField()),
                ('sizes', models.ManyToManyField(to='store.size')),
            ],
        ),
    ]
